### PR TITLE
Backport: fixed integer value auto completer #121

### PR DESCRIPTION
**Pull request by lzap**
WIP - tests via Travis CI

### CODE REVIEW

**Comment by lzap** [comment]
I am backporting this patch https://github.com/wvanbergen/scoped_search/pull/121 into 2.7.1 for the record.

**Comment by lzap** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1190601

**Comment by ohadlevy** [comment]
@abenari any chance you can have a look? thanks!

**Comment by abenari** [comment]
Lgtm

**Comment by ohadlevy** [comment]
@abenari any idea about the failing tests?

**Comment by abenari** [comment]
@ohadlevy, tests seems to fail due to an environment issue "failed to install pg".
Not going to have time to look at it in the near future. I 'll be happy to accept fixes, and issue a "new" 2.7.x release for the ruby 1.8.7 users once tests are passing.

**Comment by lzap** [comment]
Thanks for investigation, can you please create stable-2.7.1 branch upstream so I can open the PR there and fix the tests? Thanks!

**Comment by abenari** [comment]
@lzap We have a tag for each version, you can open a pull request on tag v2.7.1

**Pull request closed without merging**
